apiVersion: v1
kind: Pod
metadata:
  name: frontend-bad
  namespace: dev
spec:
  serviceAccountName: frontend-sa
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASS

