apiVersion: v1
kind: Pod
metadata:
  name: frontend-ok
  namespace: dev
spec:
  serviceAccountName: frontend-sa
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep 3600"]

