pipeline{
     agent any 
    stages{
        stage("Debug Workspace"){
            steps{
                sh "pwd"
                sh "ls -la"
                sh "ls -la service_ingress/domain_based_routing"
            }
        }
         stage("Build  images"){
            steps{
               dir("service_ingress/domain_based_routing"){
                    sh "docker build -t sudipta4docker/domain-based-routing:${BUILD_NUMBER} ."
                }
            }
            post{
                success{
                    echo "========Image build successfully========"
                    sh "docker images | grep sudipta4docker/domain-based-routing"

                }
                failure{
                    echo "========Build the images execution failed========"
                }
            }
        }
        stage("Login to docker hub"){
            steps{
                withCredentials([usernamePassword(credentialsId: '22b95ae6-c01c-4793-b12b-81ecfc1518ad', passwordVariable: 'DOCKER_ACCESS_TOKEN', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh "echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin"
                }
            }
                post{
                    success{
                        echo "========Login to docker hub successfully========"
                    }
                    failure{
                        echo "========Login to docker hub execution failed========"
                    }
                }
        }
          stage("push the images to docker hub"){
            steps{
                

                    echo "========Pushing the images to docker hub========"
                    sh "docker push sudipta4docker/domain-based-routing:${BUILD_NUMBER}"               
                
            }
        }
   
        // stage("Deploy to Kubernetes"){
        //     steps{
        //         echo "========Deploying to Kubernetes========"

        //         sh """
        //         kubectl set image deployment/k8-learing-journey-app-deployment \
        //         my-kubernetes-learing-journey-portfolio-application-image=sudipta4docker/domain-based-routing:${BUILD_NUMBER}
        //         """
        //     }
        // }
      
        // stage("Apply Deployment"){
        //     steps{
        //         echo "========Deploying to Kubernetes========"

        //         sh """
        //         kubectl apply -f 
        //         """
        //     }
        // }
        
    }
   
}