pipeline{
    agent any 

    stages{

        stage("Debug Workspace"){
            steps{
                sh "pwd"
                sh "ls -la"
                sh "ls -la service_ingress/domain_based_routing"
            }
        }

        stage("Build Image"){
            steps{
                dir("service_ingress/domain_based_routing"){
                    sh "docker build -t sudipta4docker/domain-based-routing:${BUILD_NUMBER} ."
                }
            }
        }

        stage("Docker Login"){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: '22b95ae6-c01c-4793-b12b-81ecfc1518ad',
                    passwordVariable: 'DOCKER_ACCESS_TOKEN',
                    usernameVariable: 'DOCKER_USERNAME'
                )]) {
                    sh "echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin"
                }
            }
        }

        stage("Push Image"){
            steps{
                sh "docker push sudipta4docker/domain-based-routing:${BUILD_NUMBER}"
            }
        }

        stage("Deploy to Kubernetes"){
            steps{
                withCredentials([file(
                    credentialsId: '8c0dd018-899d-4ddc-b19c-050285320f87',
                    variable: 'kube_config'
                )]) {
                    dir("service_ingress/domain_based_routing"){
                        sh """
                        export KUBECONFIG=$kube_config

                        # update YAML for deployment
                        sed -i 's|image:.*|image: sudipta4docker/domain-based-routing:${BUILD_NUMBER}|' Deployment.yaml

                        kubectl apply -f Deployment.yaml
                        kubectl rollout status deployment/k8-learing-journey-app-deployment
                        """
                    }
                }
            }
        }

        stage("Update GitHub"){
            steps{
                dir("${WORKSPACE}"){
                    sshagent(['git-ssh']) {
                        sh """
                        mkdir -p ~/.ssh
                        ssh-keyscan github.com >> ~/.ssh/known_hosts

                        # IMPORTANT: checkout first
                        git checkout main
                        git pull origin main

                        git config user.name "jenkins"
                        git config user.email "jenkins@local"

                        # update YAML for git (same change)
                        sed -i 's|image:.*|image: sudipta4docker/domain-based-routing:${BUILD_NUMBER}|' service_ingress/domain_based_routing/Deployment.yaml

                        git add service_ingress/domain_based_routing/Deployment.yaml
                        git diff --quiet || git commit -m "update image to ${BUILD_NUMBER}"
                        git push origin main
                        """
                    }
                }
            }
        }
    }
}