apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-from-clusterrole
  namespace: prod
subjects:
- kind: User
  name: test-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: minkube-node-reader  # assume a pod-reader ClusterRole exists
  apiGroup: rbac.authorization.k8s.io
