apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: dev
spec:
  serviceAccountName: frontend-sa
  containers:
  - name: frontend
    image:  bitnami/kubectl
    command: ["sleep", "3600"]
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: DB_PASS

