apiVersion: v1
kind: Pod
metadata:
  name: payment-pod
  namespace: dev
spec:
  containers:
  - name: payment
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: DB_PASSWORD # This name is user defined
      valueFrom:
        secretKeyRef:
          name: app-secret 
          key: DB_PASS

