apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sudipta4docker/domain-based-routing-backend:v2.0.1
          ports:
            - containerPort: 80

          # ✅ Readiness Probe (traffic control)
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          # ✅ Liveness Probe (restart if stuck)
          livenessProbe:
            httpGet:
              path: /api/live
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
